version: '3.8'

services:
  secure-auth:
    build:
      context: ./secure-auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - RESOURCE=${AZURE_RESOURCE}
      - CLIENTID=${AZURE_CLIENT_ID}
      - TOKEN_ENDPOINT=${AZURE_TOKEN_ENDPOINT}
      - REFRESH_TIME=600
      - SECRET_KEY=${SECRET_KEY}
      - MAX_LOGIN_ATTEMPTS=5
      - LOGIN_TIMEOUT=300
      - SESSION_LIFETIME=3600
    volumes:
      - secure_auth_data:/app/data
    networks:
      - app-network
    depends_on:
      - redis
    restart: unless-stopped

  azure-drift:
    build:
      context: ./azure-drift
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=False
      - API_RELOAD=False
      - DRIFT_COLLECTION_INTERVAL=1800
      - DRIFT_RETENTION_DAYS=30
      - DRIFT_MAX_SNAPSHOTS=1000
      - DRIFT_MAX_REPORTS=1000
      - ALLOWED_ORIGINS=*
      - MAX_REQUESTS_PER_MINUTE=60
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=azure_drift
    volumes:
      - azure_drift_data:/app/data
    networks:
      - app-network
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  celery-worker:
    build:
      context: ./azure-drift
      dockerfile: Dockerfile
    command: celery -A src.core.tasks worker --loglevel=info
    environment:
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=azure_drift
    networks:
      - app-network
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  celery-beat:
    build:
      context: ./azure-drift
      dockerfile: Dockerfile
    command: celery -A src.core.tasks beat --loglevel=info
    environment:
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=azure_drift
    networks:
      - app-network
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  flower:
    build:
      context: ./azure-drift
      dockerfile: Dockerfile
    command: celery -A src.core.tasks flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis
      - celery-worker
    restart: unless-stopped

volumes:
  secure_auth_data:
  azure_drift_data:
  redis_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge 