version: '3.8'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  celery-worker:
    build: .
    command: celery -A src.core.tasks worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=azure_drift
    depends_on:
      - redis
      - mongodb

  celery-beat:
    build: .
    command: celery -A src.core.tasks beat --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=azure_drift
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  flower:
    build: .
    command: celery -A src.core.tasks flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker

volumes:
  redis_data:
  mongodb_data: 